# Exercise 4

### Define the grid world.

In [6]:
import numpy as np

grid_world = np.full((5,5),0.0)
grid_world

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Finding state-value for each one of the states

In [7]:
def markovian(grid_shape,num_of_trials,DISCOUNT_RATE):
    for trial in range(num_of_trials): #number of times we will go through the whole grid
      for i in range(grid_shape[0]):      #all the rows
        for j in range(grid_shape[1]):    #all the columns
          #move the agent and make the value equal to 0 if we became out of the grid
          left = grid_world[i][j-1] if j > 0 else 0 
          right = grid_world[i][j+1] if j < 4 else 0

          up = grid_world[i-1][j] if i > 0 else 0
          down = grid_world[i+1][j] if i < 4 else 0

          directions = [up, down, left, right]     

          value=0
          reward_A = 10
          reward_B = 5
          if i==0 and j==1: # the position of A
            value = reward_A + DISCOUNT_RATE*grid_world[4][1]

          elif i==0 and j==3: # the position of B
            value = reward_B + DISCOUNT_RATE*grid_world[2][3]

          else:
            for direc in directions:
              # if moving to a cell in the grid
              if direc != 0: 
                value += 0.25 * (0 + DISCOUNT_RATE*direc)
              #if the agent hits a wall, it cannot move and it receives a reward of -1  
              else:
                value += 0.25 * (-1 + DISCOUNT_RATE*grid_world[i][j])

          grid_world[i][j] = value
    return grid_world

### When the number of trials is 100 and the discount rate is 0.9

In [8]:
np.round(markovian((5,5),100,0.9), 1)

array([[ 3.3,  8.8,  4.4,  5.3,  1.5],
       [ 1.5,  3. ,  2.3,  1.9,  0.5],
       [ 0.1,  0.7,  0.7,  0.4, -0.4],
       [-1. , -0.4, -0.4, -0.6, -1.2],
       [-1.9, -1.3, -1.2, -1.4, -2. ]])

### When the number of trials is 100 and the discount rate is 0.85

In [9]:
np.round(markovian((5,5),100,0.85), 1)

array([[ 2.9,  9.1,  4. ,  5.2,  1.2],
       [ 1.2,  2.7,  1.9,  1.6,  0.3],
       [-0.1,  0.6,  0.5,  0.3, -0.4],
       [-0.9, -0.4, -0.3, -0.5, -1. ],
       [-1.6, -1.1, -1. , -1.2, -1.7]])

### When the number of trials is 100 and the discount rate is 0.75

In [10]:
np.round(markovian((5,5),100,0.75), 1)

array([[ 2.2,  9.4,  3.3,  5.1,  0.7],
       [ 0.7,  2.2,  1.3,  1.2,  0.1],
       [-0.2,  0.4,  0.3,  0.2, -0.4],
       [-0.7, -0.3, -0.2, -0.3, -0.8],
       [-1.3, -0.8, -0.7, -0.8, -1.3]])